version: 3

allow:
  depOnAnyVendor: true

excludeFiles:
  - "^.*_test\\.go$"

components:
  cmd:
    in: cmd/**
  delivery:
    in: internal/delivery/**
  usecase:
    in: internal/usecase/**
  domain:
    in: internal/domain/**
  adapter:
    in:
      - internal/adapter/argocd/**
      - internal/adapter/noop/**
      - internal/adapter/prometheus/**
      - internal/adapter/loki/**
      - internal/adapter/alertmanager/**
      - internal/adapter/composite/**
  factory:
    in: internal/adapter/factory/**
  config:
    in: internal/config/**
  pkg:
    in: pkg/**
  platform:
    in: internal/platform/**
  delivery_http:
    in: internal/delivery/http/**
  adapter_postgres:
    in: internal/adapter/postgres/**

deps:
  cmd:
    anyProjectDeps: true

  delivery:
    mayDependOn:
      - usecase
      - config
      - pkg
      - domain
      - delivery_http

  usecase:
    mayDependOn:
      - domain
      - config
      - platform

  adapter:
    mayDependOn:
      - domain
      - config
      - platform

  factory:
    mayDependOn:
      - adapter
      - domain
      - config
      - platform

  domain:
    mayDependOn:
      - domain

  config:
    anyVendorDeps: true

  platform:
    mayDependOn:
      - domain
      - config

  pkg:
    mayDependOn:
      - domain
    anyVendorDeps: true

  delivery_http:
    mayDependOn:
    - usecase
    - config
    - pkg
    - domain

  adapter_postgres:
    mayDependOn:
    - domain
    - config