run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell
    - unconvert
    - bodyclose
    - noctx
  disable:
    - prealloc

linters-settings:
  gosec:
    excludes:
      - G104
    severity: medium
    confidence: medium
  revive:
    ignore-generated-header: true
    rules:
      - name: exported
        severity: warning
      - name: blank-imports
      - name: context-keys-type
      - name: error-return
  lll:
    line-length: 120
    tab-width: 1
  funlen:
    lines: 60
    statements: 40
  gocyclo:
    min-complexity: 10

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - lll
        - funlen
        - gocyclo
