log_level: info
output: human
profile: default

gitops:
  provider: noop

observability:
  provider: prometheus
  logs_provider: loki
  alerts_provider: alertmanager

profiles:
  default:
    kube_context: minikube
    gitops_url: https://argocd.example.com
    gitops_token_env: ARGOCD_AUTH_TOKEN
    gitops_insecure: false
    metrics_url: http://localhost:9090
    metrics_insecure: false
    logs_url: http://localhost:3100
    logs_insecure: false
    alerts_url: http://localhost:9093
    alerts_insecure: false
